import { loadDictionary } from "@/lib/i18n";
import { loadDomainConfig } from "@/lib/config";

export default async function MethodologyPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const dict = loadDictionary(locale);
  const config = loadDomainConfig("science");
  const sources = config.sources;

  const categories = sources.reduce<Record<string, typeof sources>>(
    (acc, s) => {
      const lang = s.language || "en";
      if (!acc[lang]) acc[lang] = [];
      acc[lang].push(s);
      return acc;
    },
    {},
  );

  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 py-8">
      <h1 className="font-heading text-2xl font-bold mb-2">
        {dict.methodology.title}
      </h1>
      <p className="text-sm text-muted-foreground mb-8">
        {dict.methodology.subtitle}
      </p>

      <article className="space-y-8">
        <section>
          <h2 className="font-heading text-lg font-semibold mb-2">
            {locale === "zh" ? "编辑理念" : "Editorial Philosophy"}
          </h2>
          <p className="text-sm leading-relaxed text-foreground/80">
            {locale === "zh"
              ? '我们坚持"一手信源，如实呈现"的原则。所有信息均来自经过验证的权威科学出版物和科研机构官方渠道，不炸裂、不夸张、不接商单。'
              : 'We adhere to "first-hand sources, presented as-is." All information comes from verified authoritative scientific publications and official research institution channels. No sensationalism, no exaggeration, no sponsored content.'}
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-semibold mb-3">
            {locale === "zh" ? "信息来源" : "Sources"}
          </h2>
          {Object.entries(categories).map(([lang, items]) => (
            <div key={lang} className="mb-4">
              <h3 className="text-xs font-medium text-primary/70 tracking-wider uppercase mb-2">
                {lang === "zh" ? "中文源" : "English Sources"}
              </h3>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
                {items.map((s) => (
                  <li
                    key={s.id}
                    className="flex items-center gap-2 text-sm rounded-md px-2 py-1 hover:bg-accent/40 transition-colors"
                  >
                    <span className="h-1.5 w-1.5 rounded-full bg-primary shrink-0" />
                    <span>{s.name}</span>
                    <span className="text-[10px] text-highlight font-mono ml-auto">
                      ×{s.weight}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </section>

        <section>
          <h2 className="font-heading text-lg font-semibold mb-2">
            {locale === "zh" ? "筛选机制" : "Selection Mechanism"}
          </h2>
          <p className="text-sm leading-relaxed text-foreground/80">
            {locale === "zh"
              ? "我们采用双层筛选：第一层基于多维评分（跨源交叉验证、源权威度、时效性），第二层由 AI 进行主题相关性判断和噪音过滤。最终由高级 AI 模型生成深度摘要和一句话快讯。"
              : "We use a two-layer filtering system: the first layer is based on multi-dimensional scoring (cross-source verification, source authority, timeliness), and the second layer uses AI for topic relevance assessment and noise filtering. Final summaries are generated by advanced AI models."}
          </p>
        </section>

        <section>
          <h2 className="font-heading text-lg font-semibold mb-2">
            {locale === "zh" ? "中立原则" : "Neutrality Principles"}
          </h2>
          <p className="text-sm leading-relaxed text-foreground/80">
            {locale === "zh"
              ? "我们不持有任何科学立场，忠实报道研究成果本身。对于存在争议的科学话题，我们会呈现多方观点，并标注争议所在。所有 AI 生成的摘要均附有原始来源链接，供读者追溯和验证。"
              : "We do not hold any scientific position and faithfully report research findings. For controversial scientific topics, we present multiple viewpoints and note the controversy. All AI-generated summaries include links to original sources for reader verification."}
          </p>
        </section>
      </article>
    </div>
  );
}
